version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.4.0
    hostname: elasticsearch
    environment:
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      # - http.host=0.0.0.0
      # - transport.host=127.0.0.1
      # - network.host=_local_
      - network.publish_host=127.0.0.1
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      nproc: 65536
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    # volumes:
    #   - ./data/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200